apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-net-ingress
  namespace: homework
  annotations:
    nginx.org/rewrites: "serviceName=kube-net-service rewrite=/index.html"
spec:
  ingressClassName: nginx
  rules:
  - host: homework.otus
    http:
      paths:
      - path: /homepage
        pathType: Exact
        backend:
          service:
            name: kube-net-service
            port:
              number: 80
      - path: /
        pathType: Exact
        backend:
          service:
            name: kube-net-service
            port:
              number: 80