apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-mon-app
  labels:
    app: kube-mon-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kube-mon-app
  template:
    metadata:
      labels:
        app: kube-mon-app
    spec:
      containers:
      - name: kube-mon-app
        image: nginx:1.29.3
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/metrics.conf
          subPath: metrics.conf
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.3.0
        args:
          - "-nginx.scrape-uri=http://127.0.0.1:8080/metrics_stub"
        ports:
          - name: metrics
            containerPort: 9113
      volumes:
      - name: workdir
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-conf-configmap
