# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-net-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: homework.otus
    http:
      paths:
      - path: /metrics_stub
        pathType: Prefix
        backend:
          service:
            name: kube-mon-svc
            port:
              number: 8080