apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-templating.fullname" . }}-service
  namespace: homework
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "kubernetes-templating.fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}