apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-net-app
  namespace: homework
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kube-net-app
  template:
    metadata:
      labels:
        app: kube-net-app
    spec:
      serviceAccountName: monitoring
      initContainers:
      - name: init-container
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/init/metrics.html"
        - http://kube-dns.kube-system.svc.cluster.local:9153/metrics
        volumeMounts:
        - name: workdir
          mountPath: "/init"
      containers:
      - name: kube-net-app
        image: nginx:1.29.2
        lifecycle:
          preStop:
            exec:
              command: ["rm", "/homework/metrics.html"]
        readinessProbe:
          exec:
            command:
            - cat
            - /homework/metrics.html
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: workdir
          mountPath: "/homework"
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: workdir
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-conf-configmap
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      ##      nodeSelectorTerms:
      #     - matchExpressions:
      #        - key: homework
      #          operator: In
      #          values:
      #          - "true"
        