apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1URXhNekU1TlRBME5Gb1hEVE0xTVRFeE1qRTVOVEEwTkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTC9GCjVIc3JubVdIbVc4L09kMEZwWjF3M0JNSDJWb2pZUXlSMmNDWFg5T3htbStIVFgvTEFwWUVJdGlLS1FlbXJQMWwKRDkyOUFtUk95dWg0aEMxalZuMGpBTkJDZDFUN015Y1dsNmlPUld1S25xdnJERDhDcStyM216TWlwZVNheDRqRQp6aWtoR1pnNFMxVnJmS21zdUJFcVNoOE80ZjhzSlQwaXhqekc3WitVUVBES0pCVG1odXVIUDBaU3FKRXhWUXFlCnpYN3JSK2JvWXRMTWZRL2pURUNOdWxkWitmcWRjSlZoeFNtM082YStvaHlzcjRuYzJ4a251Y0RkYnFJa2dHZTMKTGc4RXdEZTlyUERBbHN1NkpUSEZZckJQdXowNlRPbWJ3dW1qUkZoTWhXMkRzUmJ2RSsxOFJTdTJKQnJpdFk3VQpkYVo5L1VFMGpLVW8reGtzclUwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRMlNueVFtMDVVWExPQTdOTnVlTXpnbmhLWDBEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFPU1pTbnhiQwpGTlBTY1NVLzFybkFMSm00eS9OTiszQ0FBY29qMVFrWTB2akhRZkxsOEYyOHNaTVZmalg4REVnamRJQk1hdk85CmJSMXc5aEJlRWh1Wi9FVGlLMDRzekZ6by9YQnhhQzQxVEhOblJRNVBCeHJUblR6TXBzbk5pVGE4Qm01OTl2bm8KS2R6OGFxcVRxWUNSUGpwSk1HVm56aXh3bVFpN1IvaXVOMUJ3UEpQdnpPMW1Da0dwWC9nZGJoUUdzNG90REJmbwpraVdZTnlHa05zZ0w3Z1hVeTZGZk1VRVVWQlZscU1wWnJ2RWR6NFYvekY1b1hDdVlnNGdQZmtNZm04aTd6L2RjCk1PQWNqdzJ1bTBSdE5OQzRFOVhKYzk5MHc3QkZLRnMwaTMxdEZxWEhWbThVbFl1bWd6VkFzS1VhQnYvc2Q1RHYKT1VXZ1U5WWdoTW0xY0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: homework
    user: cd
  name: cd
current-context: cd
kind: Config
users:
- name: cd
  user:
    tokenFile: token
