apiVersion: v1
kind: Service
metadata:
  name: kube-intro-service
  namespace: homework
spec:
  type: NodePort
  selector:
    app: kube-controller-app
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 32140