apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homework
  name: kube-volume-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: homework.otus
    http:
      paths:
      - path: /conf/file
        pathType: Prefix
        backend:
          service:
            name: kube-volume-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-volume-service
            port:
              number: 80